name: Deploy Client Project With Render

on:
    push:
        branches: [main]
        paths:
            - 'client/**'
    workflow_dispatch:
            
jobs:
    deploy-client:
        runs-on: ubuntu-latest

        steps:
        - name: Render Deploy Client
          run: curl ${{ secrets.RENDER_CLIENT_HOOK }}